### ISSUE TITLE
QMK support?

### ISSUE THREAD

**Issue by djl** [brow/balbuzard#2]
Is there support for the Balbuzard in QMK or are there any plans to add it?

I noticed you have [a fork of QMK](https://github.com/brow/qmk_firmware) with some related commits in it but this doesn't seem to be up to date, at least the low profile variant.

Just asking before I submit an order for some PCBs only to discover it's not maintained anymore (which would really suck as this seems like the ideal keyboard for me!)

Apologies if this is already documented somewhere and I just missed it!

**Comment by brow** [comment]
Thanks for bringing this up! It was a good reminder to [add firmware links to the README](https://github.com/brow/balbuzard/pull/3).

I think the QMK branch you want is [brow/qmk_firmware@balbuzard-0.2](https://github.com/brow/qmk_firmware/tree/balbuzard-0.2).

**Comment by djl** [comment]
That's what I was looking for. No idea how I missed it 😄 

Looks like it may need some updates to work with the latest QMK. If I get it working would you be opposed to me submitting it upstream to QMK so others could use it?
